use_default_settings: true

general:
  debug: false
  instance_name: "Forge0 Search"

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"
  formats:
    - html
    - json

server:
  secret_key: "forge0-super-secret-key-change-me"
  limiter: false
  image_proxy: false
  bind_address: "0.0.0.0"
  port: 8080

ui:
  default_theme: simple
  static_use_hash: true

outgoing:
  request_timeout: 10.0
  max_request_timeout: 15.0
  pool_connections: 100
  pool_maxsize: 20
